name: Check Docker and Git Versions

on:
  push:
    branches:
      - main
  
jobs:
  version-check:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Docker version
      run: docker --version

    - name: Get Git version
      run: git --version
